# Generated by Django 6.0 on 2025-12-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmemory',
            name='agent_type',
            field=models.CharField(db_index=True, default='main', help_text="Type of agent: 'main', 'post', 'tutorial'", max_length=50),
        ),
        migrations.AddIndex(
            model_name='agentmemory',
            index=models.Index(fields=['agent_type', 'created_at'], name='mysql_model_agent_t_c51362_idx'),
        ),
    ]
